{% set name = "csdms-permamodel-ku" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/permamodel
  git_rev: v{{ version }}

requirements:
  build:
    - bmi-babel
    - permamodel
  run:
    - bmi-babel
    - permamodel
    - matplotlib

test:
  requires:
    - pymt

about:
  home: https://csdms.colorado.edu/wiki/Model:Kudryavtsev_Model
  license: MIT
  summary: The point version of the Kudryavtsev model from Permamodel.
  dev_url: https://github.com/permamodel/permamodel
