{% set name = "csdms-permamodel-ku" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1

source:
  git_url: https://github.com/permamodel/permamodel
  git_rev: v{{ version }}

requirements:
  build:
    - babelizer
    - permamodel
  run:
    - cca-babel <2
    - cca-spec-babel
    - permamodel

test:
  requires:
    - netcdf-fortran=4.4.4=5  # tmp fix for ESMF
    - pymt

about:
  home: https://csdms.colorado.edu/wiki/Model:Kudryavtsev_Model
  license: MIT
  summary: The point version of the Kudryavtsev model from Permamodel.
  dev_url: https://github.com/permamodel/permamodel
